id: AD7F99499
base_file: f9BAB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:04:10.422244
  last_modified_at: 2022-05-30 21:04:10.422248
