id: AD7F99499
base_file: fA57A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:04:10.426674
  last_modified_at: 2022-05-30 21:04:10.426677
