id: AD7F99499
base_file: fE33F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:04:10.442923
  last_modified_at: 2022-05-30 21:04:10.442927
